service: safeword

frameworkVersion: ">=1.8.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource: "*"
  environment:
    PHONE_NUMBER: ${opt:number}
    NAME: ${opt:name}
    PI_ENDPOINT: "https://748bbbf3.ngrok.io/start"
    VIDEO_ENDPOINT: "https://kf9zxc5wj0.execute-api.us-east-1.amazonaws.com/safeword/videos"
    TEXT_ENDPOINT:  "https://kf9zxc5wj0.execute-api.us-east-1.amazonaws.com/safeword/text"
    BUCKET_NAME: "safeword-storage"
    APP_ID: 'amzn1.ask.skill.80e3c59c-3c64-400e-ab87-134d4a1ac1b4'

functions:
  main:
    handler: main/index.handler
  recordVideo:
    handler: recordVideo/index.handler
  text:
    handler: text/index.handler
    events:
      - http:
          path: /text
          method: post
  getVideos:
    handler: getVideos/index.handler
    events:
      - http:
          path: /videos
          method: get