service: safeword

frameworkVersion: ">=1.8.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource: "*"
  environment:
    PHONE_NUMBER: ${opt:number}
    NAME: ${opt:name}
    PI_ENDPOINT: "https://a7f3f473.ngrok.io/start"
    VIDEO_ENDPOINT: "https://9m5fe3vaq7.execute-api.us-east-1.amazonaws.com/safeword/videos"
    TEXT_ENDPOINT:  "https://9m5fe3vaq7.execute-api.us-east-1.amazonaws.com/safeword/text"
    BUCKET_NAME: "safeword-storage"

functions:
  main:
    handler: main/index.handler
  text:
    handler: text/index.handler
    events:
      - http:
          path: /text
          method: post
  recordVideo:
    handler: recordVideo/index.handler
    events:
      - http:
          path: /record
          method: post
  getVideos:
    handler: getVideos/index.handler
    events:
      - http:
          path: /videos
          method: get